# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target '仿网易新闻' do
	 pod 'AFNetworking', '~> 3.1.0'
	 pod 'YYModel'
	 pod 'SDWebImage'
	 pod 'Masonry'
	
end
